name: Code Review

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  code_review:
    name: 'Code Review'
    runs-on: ubuntu-latest

    permissions:
      contents: read 
      pull-requests: write # required for commenting in PR
 
    steps:
      - name: Code review
        uses: ai-dream-ua/crs-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # required for commenting in PR
          crs-api-token: ${{ secrets.CRS_API_TOKEN }} # contact CRS team to get the token
          exclude: "**/*.md, **/package*.json, **/*.*rc" # exclude files from review process
